module.exports = {
    UsersControllers: require('./users_controllers'),
    ShopsControllers: require('./shops_controllers'),
    AddressController: require('./reverseGeocode'),
    AdminController: require('./admin_controller'),
    BannerController: require('./banner_controller'),
    DoctorController: require('./doctors_controller'),
    DoctorAuthController: require('./doctor_auth_controller'),
    ClinicController: require('./clinic_controller'),
    AppointmentController: require('./appointment_controller'),
    SpecializationController: require('./specilization_controller'),
    ProductController: require('./product_controller'),
    CategoryController: require('./category_controller'),
    SubcategoryController: require('./subcategory_controller'),
    BrandController: require('./brand_controller'),
    CartController: require('./cart_controller'),
    WishlistController: require('./wishlist_controller'),
    DiscountController: require('./discount_controller'),
    DiscountedUserController: require('./discounteduser_controller'),
    DiscountedProductController: require('./discountedproduct_controller'),
    OrderController: require('./order_controller'),
    FileController: require('./file_controller'),
    DashboardController: require('./dashboard_controller'),
    PrescriptionController: require('./prescription_controller'),
}