
module.exports = {
    Otps: 'otps',
    Users: 'users',
    Files: 'files',
    Admins: 'admins',
    Banners: 'banners',
    Doctors: 'doctors',
    Doctorsavailabilities: 'doctorsavailabilities',
    Adresses: 'addresses',
    Clinics: 'clinics',
    Clinicdoctors: 'clinicdoctors',
    Appointments: 'appointments',
    Reviews: 'reviews',
    DoctorSpecializations: 'doctor_specializations',
    Products: 'products',
    Carts: 'carts',
    Wishlists: 'wishlists',
    Brands: 'brands',
    Categories: 'categories',
    Discounts: 'discounts',
    DiscountedUsers: 'discountedusers',
    DiscountedProducts: 'discountedproducts',
    Subcategories: 'subcategories',
    ProductImages: 'product_images',
    Orders: 'orders',
    OrderItems: 'order_items',
    Payments: 'payments',
    prescriptions: 'prescriptions'

}